# Generated by Django 5.1.7 on 2025-03-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='thumbnail_path',
            new_name='thumbnail_file',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_path',
            new_name='video_file',
        ),
    ]
