# Generated by Django 5.1.7 on 2025-03-21 19:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_rename_thumbnail_path_video_thumbnail_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uploaded_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='duration_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_file',
            field=models.FileField(null=True, upload_to='thumbnails/'),
        ),
    ]
