# Generated by Django 5.1.7 on 2025-03-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_uploaded_on_alter_video_duration_sec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail_file',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
