# Generated by Django 5.1.7 on 2025-03-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_video_thumbnail_file_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='num_likes',
            field=models.IntegerField(default=0),
        ),
    ]
