# Generated by Django 5.1.7 on 2025-03-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_video_num_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='num_comments',
            field=models.IntegerField(default=0),
        ),
    ]
