# Generated by Django 5.2.13 on 2026-05-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0009_video_num_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="transcode_status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
